// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter_Resize.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_Resize::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_Resize::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> image_filter_Resize::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> image_filter_Resize::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> image_filter_Resize::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_Resize::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_Resize::ap_const_lv32_1 = "1";

image_filter_Resize::image_filter_Resize(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_image_filter_Resize_opr_linear_fu_44 = new image_filter_Resize_opr_linear("grp_image_filter_Resize_opr_linear_fu_44");
    grp_image_filter_Resize_opr_linear_fu_44->ap_clk(ap_clk);
    grp_image_filter_Resize_opr_linear_fu_44->ap_rst(ap_rst);
    grp_image_filter_Resize_opr_linear_fu_44->ap_start(grp_image_filter_Resize_opr_linear_fu_44_ap_start);
    grp_image_filter_Resize_opr_linear_fu_44->ap_done(grp_image_filter_Resize_opr_linear_fu_44_ap_done);
    grp_image_filter_Resize_opr_linear_fu_44->ap_idle(grp_image_filter_Resize_opr_linear_fu_44_ap_idle);
    grp_image_filter_Resize_opr_linear_fu_44->ap_ready(grp_image_filter_Resize_opr_linear_fu_44_ap_ready);
    grp_image_filter_Resize_opr_linear_fu_44->p_src_rows_V_read(grp_image_filter_Resize_opr_linear_fu_44_p_src_rows_V_read);
    grp_image_filter_Resize_opr_linear_fu_44->p_src_cols_V_read(grp_image_filter_Resize_opr_linear_fu_44_p_src_cols_V_read);
    grp_image_filter_Resize_opr_linear_fu_44->p_src_data_stream_V_dout(grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_dout);
    grp_image_filter_Resize_opr_linear_fu_44->p_src_data_stream_V_empty_n(grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_empty_n);
    grp_image_filter_Resize_opr_linear_fu_44->p_src_data_stream_V_read(grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_read);
    grp_image_filter_Resize_opr_linear_fu_44->p_dst_rows_V_read(grp_image_filter_Resize_opr_linear_fu_44_p_dst_rows_V_read);
    grp_image_filter_Resize_opr_linear_fu_44->p_dst_cols_V_read(grp_image_filter_Resize_opr_linear_fu_44_p_dst_cols_V_read);
    grp_image_filter_Resize_opr_linear_fu_44->p_dst_data_stream_V_din(grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_din);
    grp_image_filter_Resize_opr_linear_fu_44->p_dst_data_stream_V_full_n(grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_full_n);
    grp_image_filter_Resize_opr_linear_fu_44->p_dst_data_stream_V_write(grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_write);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_43);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_71);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_71 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_ap_start);
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_dst_cols_V_read);
    sensitive << ( cols );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_full_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_dst_rows_V_read);
    sensitive << ( rows );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_cols_V_read);
    sensitive << ( cols );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_dout);
    sensitive << ( p_src_data_stream_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_empty_n);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_rows_V_read);
    sensitive << ( rows );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_src_data_stream_V_read);
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_43 );
    sensitive << ( grp_image_filter_Resize_opr_linear_fu_44_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_Resize_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, p_src_data_stream_V_dout, "(port)p_src_data_stream_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_V_empty_n, "(port)p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_V_read, "(port)p_src_data_stream_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, ap_sig_bdd_43, "ap_sig_bdd_43");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_ap_start, "grp_image_filter_Resize_opr_linear_fu_44_ap_start");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_ap_done, "grp_image_filter_Resize_opr_linear_fu_44_ap_done");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_ap_idle, "grp_image_filter_Resize_opr_linear_fu_44_ap_idle");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_ap_ready, "grp_image_filter_Resize_opr_linear_fu_44_ap_ready");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_src_rows_V_read, "grp_image_filter_Resize_opr_linear_fu_44_p_src_rows_V_read");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_src_cols_V_read, "grp_image_filter_Resize_opr_linear_fu_44_p_src_cols_V_read");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_dout, "grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_dout");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_empty_n, "grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_read, "grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_read");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_dst_rows_V_read, "grp_image_filter_Resize_opr_linear_fu_44_p_dst_rows_V_read");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_dst_cols_V_read, "grp_image_filter_Resize_opr_linear_fu_44_p_dst_cols_V_read");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_din, "grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_full_n, "grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_write, "grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg, "grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_71, "ap_sig_bdd_71");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_Resize::~image_filter_Resize() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_image_filter_Resize_opr_linear_fu_44;
}

void image_filter_Resize::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_Resize_opr_linear_fu_44_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_43.read())) {
            grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_image_filter_Resize_opr_linear_fu_44_ap_ready.read())) {
            grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
}

void image_filter_Resize::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_Resize_opr_linear_fu_44_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_Resize_opr_linear_fu_44_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_Resize::thread_ap_sig_bdd_43() {
    ap_sig_bdd_43 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_Resize::thread_ap_sig_bdd_71() {
    ap_sig_bdd_71 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_Resize::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_71.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_ap_start() {
    grp_image_filter_Resize_opr_linear_fu_44_ap_start = grp_image_filter_Resize_opr_linear_fu_44_ap_start_ap_start_reg.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_dst_cols_V_read() {
    grp_image_filter_Resize_opr_linear_fu_44_p_dst_cols_V_read = cols.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_full_n() {
    grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_full_n = p_dst_data_stream_V_full_n.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_dst_rows_V_read() {
    grp_image_filter_Resize_opr_linear_fu_44_p_dst_rows_V_read = rows.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_cols_V_read() {
    grp_image_filter_Resize_opr_linear_fu_44_p_src_cols_V_read = cols.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_dout() {
    grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_dout = p_src_data_stream_V_dout.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_empty_n() {
    grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_empty_n = p_src_data_stream_V_empty_n.read();
}

void image_filter_Resize::thread_grp_image_filter_Resize_opr_linear_fu_44_p_src_rows_V_read() {
    grp_image_filter_Resize_opr_linear_fu_44_p_src_rows_V_read = rows.read();
}

void image_filter_Resize::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_din.read();
}

void image_filter_Resize::thread_p_dst_data_stream_V_write() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        p_dst_data_stream_V_write = grp_image_filter_Resize_opr_linear_fu_44_p_dst_data_stream_V_write.read();
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_p_src_data_stream_V_read() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        p_src_data_stream_V_read = grp_image_filter_Resize_opr_linear_fu_44_p_src_data_stream_V_read.read();
    } else {
        p_src_data_stream_V_read = ap_const_logic_0;
    }
}

void image_filter_Resize::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_43.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_image_filter_Resize_opr_linear_fu_44_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

