// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter_Mat2AXIvideo_8_1080_1920_0_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_ST_st5_fsm_3 = "1000";
const sc_lv<32> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv1_1 = "1";
const sc_lv<32> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv32_1 = "1";
const sc_lv<32> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv32_2 = "10";
const sc_lv<1> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv1_0 = "0";
const sc_lv<11> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv11_0 = "00000000000";
const sc_lv<32> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv32_3 = "11";
const sc_lv<11> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv11_7FF = "11111111111";
const sc_lv<11> image_filter_Mat2AXIvideo_8_1080_1920_0_s::ap_const_lv11_1 = "1";

image_filter_Mat2AXIvideo_8_1080_1920_0_s::image_filter_Mat2AXIvideo_8_1080_1920_0_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( img_data_stream_V_dout );
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( axi_last_V_reg_249 );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_user_V_fu_88 );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ioackin_OUTPUT_STREAM_TREADY );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond7_i_fu_173_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond7_i_fu_173_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_116);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_52);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_66);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_77);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_85);
    sensitive << ( img_data_stream_V_empty_n );
    sensitive << ( exitcond_i_reg_240 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_77 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_23 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_66 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_3);
    sensitive << ( ap_sig_bdd_116 );

    SC_METHOD(thread_ap_sig_ioackin_OUTPUT_STREAM_TREADY);
    sensitive << ( OUTPUT_STREAM_TREADY );
    sensitive << ( ap_reg_ioackin_OUTPUT_STREAM_TREADY );

    SC_METHOD(thread_axi_last_V_fu_195_p2);
    sensitive << ( p_1_i_reg_151 );
    sensitive << ( r_V_fu_162_p2 );
    sensitive << ( exitcond_i_fu_184_p2 );
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_sig_ioackin_OUTPUT_STREAM_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_exitcond7_i_fu_173_p2);
    sensitive << ( rows );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( p_i_reg_140 );

    SC_METHOD(thread_exitcond_i_fu_184_p2);
    sensitive << ( cols );
    sensitive << ( p_1_i_reg_151 );
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_sig_ioackin_OUTPUT_STREAM_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_i_V_fu_178_p2);
    sensitive << ( p_i_reg_140 );

    SC_METHOD(thread_img_data_stream_V_read);
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_sig_ioackin_OUTPUT_STREAM_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_j_V_fu_189_p2);
    sensitive << ( p_1_i_reg_151 );

    SC_METHOD(thread_r_V_fu_162_p2);
    sensitive << ( cols );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_52 );
    sensitive << ( exitcond7_i_fu_173_p2 );
    sensitive << ( exitcond_i_fu_184_p2 );
    sensitive << ( exitcond_i_reg_240 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_bdd_85 );
    sensitive << ( ap_sig_ioackin_OUTPUT_STREAM_TREADY );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ioackin_OUTPUT_STREAM_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_Mat2AXIvideo_8_1080_1920_0_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, img_data_stream_V_dout, "(port)img_data_stream_V_dout");
    sc_trace(mVcdFile, img_data_stream_V_empty_n, "(port)img_data_stream_V_empty_n");
    sc_trace(mVcdFile, img_data_stream_V_read, "(port)img_data_stream_V_read");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_23, "ap_sig_bdd_23");
    sc_trace(mVcdFile, p_1_i_reg_151, "p_1_i_reg_151");
    sc_trace(mVcdFile, ap_sig_bdd_52, "ap_sig_bdd_52");
    sc_trace(mVcdFile, r_V_fu_162_p2, "r_V_fu_162_p2");
    sc_trace(mVcdFile, exitcond7_i_fu_173_p2, "exitcond7_i_fu_173_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_66, "ap_sig_bdd_66");
    sc_trace(mVcdFile, i_V_fu_178_p2, "i_V_fu_178_p2");
    sc_trace(mVcdFile, i_V_reg_235, "i_V_reg_235");
    sc_trace(mVcdFile, exitcond_i_fu_184_p2, "exitcond_i_fu_184_p2");
    sc_trace(mVcdFile, exitcond_i_reg_240, "exitcond_i_reg_240");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_77, "ap_sig_bdd_77");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_sig_bdd_85, "ap_sig_bdd_85");
    sc_trace(mVcdFile, ap_sig_ioackin_OUTPUT_STREAM_TREADY, "ap_sig_ioackin_OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, j_V_fu_189_p2, "j_V_fu_189_p2");
    sc_trace(mVcdFile, axi_last_V_fu_195_p2, "axi_last_V_fu_195_p2");
    sc_trace(mVcdFile, axi_last_V_reg_249, "axi_last_V_reg_249");
    sc_trace(mVcdFile, p_i_reg_140, "p_i_reg_140");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_3, "ap_sig_cseq_ST_st5_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_116, "ap_sig_bdd_116");
    sc_trace(mVcdFile, tmp_user_V_fu_88, "tmp_user_V_fu_88");
    sc_trace(mVcdFile, ap_reg_ioackin_OUTPUT_STREAM_TREADY, "ap_reg_ioackin_OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

image_filter_Mat2AXIvideo_8_1080_1920_0_s::~image_filter_Mat2AXIvideo_8_1080_1920_0_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_OUTPUT_STREAM_TREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
              esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
              !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))))) {
            ap_reg_ioackin_OUTPUT_STREAM_TREADY = ap_const_logic_0;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
                     !(ap_sig_bdd_85.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, OUTPUT_STREAM_TREADY.read())))) {
            ap_reg_ioackin_OUTPUT_STREAM_TREADY = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             !esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
             esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
                     !esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
         esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0))) {
        p_1_i_reg_151 = j_V_fu_189_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0))) {
        p_1_i_reg_151 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_3.read())) {
        p_i_reg_140 = i_V_reg_235.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_52.read())) {
        p_i_reg_140 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        tmp_user_V_fu_88 = ap_const_lv1_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !ap_sig_bdd_52.read())) {
        tmp_user_V_fu_88 = ap_const_lv1_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0))) {
        axi_last_V_reg_249 = axi_last_V_fu_195_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        exitcond_i_reg_240 = exitcond_i_fu_184_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_V_reg_235 = i_V_fu_178_p2.read();
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = img_data_stream_V_dout.read();
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = ap_const_lv1_0;
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = ap_const_lv1_0;
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = ap_const_lv1_1;
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = axi_last_V_reg_249.read();
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = ap_const_lv1_0;
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = tmp_user_V_fu_88.read();
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_OUTPUT_STREAM_TVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(ap_sig_bdd_85.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_OUTPUT_STREAM_TREADY.read())))) {
        OUTPUT_STREAM_TVALID = ap_const_logic_1;
    } else {
        OUTPUT_STREAM_TVALID = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_bdd_116() {
    ap_sig_bdd_116 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_bdd_23() {
    ap_sig_bdd_23 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_bdd_52() {
    ap_sig_bdd_52 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_bdd_66() {
    ap_sig_bdd_66 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_bdd_77() {
    ap_sig_bdd_77 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_bdd_85() {
    ap_sig_bdd_85 = (esl_seteq<1,1,1>(img_data_stream_V_empty_n.read(), ap_const_logic_0) && esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_77.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_23.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_66.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_cseq_ST_st5_fsm_3() {
    if (ap_sig_bdd_116.read()) {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_3 = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_sig_ioackin_OUTPUT_STREAM_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_OUTPUT_STREAM_TREADY.read())) {
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY.read();
    } else {
        ap_sig_ioackin_OUTPUT_STREAM_TREADY = ap_const_logic_1;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_axi_last_V_fu_195_p2() {
    axi_last_V_fu_195_p2 = (!p_1_i_reg_151.read().is_01() || !r_V_fu_162_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(p_1_i_reg_151.read() == r_V_fu_162_p2.read());
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_exitcond7_i_fu_173_p2() {
    exitcond7_i_fu_173_p2 = (!p_i_reg_140.read().is_01() || !rows.read().is_01())? sc_lv<1>(): sc_lv<1>(p_i_reg_140.read() == rows.read());
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_exitcond_i_fu_184_p2() {
    exitcond_i_fu_184_p2 = (!p_1_i_reg_151.read().is_01() || !cols.read().is_01())? sc_lv<1>(): sc_lv<1>(p_1_i_reg_151.read() == cols.read());
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_i_V_fu_178_p2() {
    i_V_fu_178_p2 = (!p_i_reg_140.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_i_reg_140.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_img_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
        img_data_stream_V_read = ap_const_logic_1;
    } else {
        img_data_stream_V_read = ap_const_logic_0;
    }
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_j_V_fu_189_p2() {
    j_V_fu_189_p2 = (!p_1_i_reg_151.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(p_1_i_reg_151.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_r_V_fu_162_p2() {
    r_V_fu_162_p2 = (!cols.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<11>(): (sc_biguint<11>(cols.read()) + sc_bigint<11>(ap_const_lv11_7FF));
}

void image_filter_Mat2AXIvideo_8_1080_1920_0_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_52.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond7_i_fu_173_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !((ap_sig_bdd_85.read() || 
  (esl_seteq<1,1,1>(exitcond_i_reg_240.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_OUTPUT_STREAM_TREADY.read()))) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !esl_seteq<1,1,1>(exitcond_i_fu_184_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st5_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

