// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "image_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<8> image_filter::ap_const_lv8_0 = "00000000";
const sc_lv<1> image_filter::ap_const_lv1_0 = "0";
const sc_lv<32> image_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> image_filter::ap_const_lv32_B = "1011";
const sc_logic image_filter::ap_const_logic_1 = sc_dt::Log_1;
const bool image_filter::ap_true = true;
const sc_logic image_filter::ap_const_logic_0 = sc_dt::Log_0;

image_filter::image_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    image_filter_AXIvideo2Mat_U0 = new image_filter_AXIvideo2Mat("image_filter_AXIvideo2Mat_U0");
    image_filter_AXIvideo2Mat_U0->ap_clk(ap_clk);
    image_filter_AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    image_filter_AXIvideo2Mat_U0->ap_start(image_filter_AXIvideo2Mat_U0_ap_start);
    image_filter_AXIvideo2Mat_U0->ap_done(image_filter_AXIvideo2Mat_U0_ap_done);
    image_filter_AXIvideo2Mat_U0->ap_continue(image_filter_AXIvideo2Mat_U0_ap_continue);
    image_filter_AXIvideo2Mat_U0->ap_idle(image_filter_AXIvideo2Mat_U0_ap_idle);
    image_filter_AXIvideo2Mat_U0->ap_ready(image_filter_AXIvideo2Mat_U0_ap_ready);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TDATA(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TVALID(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TREADY(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TKEEP(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TSTRB(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TUSER(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TLAST(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TID(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID);
    image_filter_AXIvideo2Mat_U0->INPUT_STREAM_TDEST(image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST);
    image_filter_AXIvideo2Mat_U0->rows(image_filter_AXIvideo2Mat_U0_rows);
    image_filter_AXIvideo2Mat_U0->cols(image_filter_AXIvideo2Mat_U0_cols);
    image_filter_AXIvideo2Mat_U0->img_data_stream_0_V_din(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din);
    image_filter_AXIvideo2Mat_U0->img_data_stream_0_V_full_n(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n);
    image_filter_AXIvideo2Mat_U0->img_data_stream_0_V_write(image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write);
    image_filter_AXIvideo2Mat_U0->img_data_stream_1_V_din(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din);
    image_filter_AXIvideo2Mat_U0->img_data_stream_1_V_full_n(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n);
    image_filter_AXIvideo2Mat_U0->img_data_stream_1_V_write(image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write);
    image_filter_AXIvideo2Mat_U0->img_data_stream_2_V_din(image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din);
    image_filter_AXIvideo2Mat_U0->img_data_stream_2_V_full_n(image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n);
    image_filter_AXIvideo2Mat_U0->img_data_stream_2_V_write(image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write);
    image_filter_CvtColor_U0 = new image_filter_CvtColor("image_filter_CvtColor_U0");
    image_filter_CvtColor_U0->ap_clk(ap_clk);
    image_filter_CvtColor_U0->ap_rst(ap_rst_n_inv);
    image_filter_CvtColor_U0->ap_start(image_filter_CvtColor_U0_ap_start);
    image_filter_CvtColor_U0->ap_done(image_filter_CvtColor_U0_ap_done);
    image_filter_CvtColor_U0->ap_continue(image_filter_CvtColor_U0_ap_continue);
    image_filter_CvtColor_U0->ap_idle(image_filter_CvtColor_U0_ap_idle);
    image_filter_CvtColor_U0->ap_ready(image_filter_CvtColor_U0_ap_ready);
    image_filter_CvtColor_U0->rows(image_filter_CvtColor_U0_rows);
    image_filter_CvtColor_U0->cols(image_filter_CvtColor_U0_cols);
    image_filter_CvtColor_U0->p_src_data_stream_0_V_dout(image_filter_CvtColor_U0_p_src_data_stream_0_V_dout);
    image_filter_CvtColor_U0->p_src_data_stream_0_V_empty_n(image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n);
    image_filter_CvtColor_U0->p_src_data_stream_0_V_read(image_filter_CvtColor_U0_p_src_data_stream_0_V_read);
    image_filter_CvtColor_U0->p_src_data_stream_1_V_dout(image_filter_CvtColor_U0_p_src_data_stream_1_V_dout);
    image_filter_CvtColor_U0->p_src_data_stream_1_V_empty_n(image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n);
    image_filter_CvtColor_U0->p_src_data_stream_1_V_read(image_filter_CvtColor_U0_p_src_data_stream_1_V_read);
    image_filter_CvtColor_U0->p_src_data_stream_2_V_dout(image_filter_CvtColor_U0_p_src_data_stream_2_V_dout);
    image_filter_CvtColor_U0->p_src_data_stream_2_V_empty_n(image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n);
    image_filter_CvtColor_U0->p_src_data_stream_2_V_read(image_filter_CvtColor_U0_p_src_data_stream_2_V_read);
    image_filter_CvtColor_U0->p_dst_data_stream_V_din(image_filter_CvtColor_U0_p_dst_data_stream_V_din);
    image_filter_CvtColor_U0->p_dst_data_stream_V_full_n(image_filter_CvtColor_U0_p_dst_data_stream_V_full_n);
    image_filter_CvtColor_U0->p_dst_data_stream_V_write(image_filter_CvtColor_U0_p_dst_data_stream_V_write);
    image_filter_Resize_U0 = new image_filter_Resize("image_filter_Resize_U0");
    image_filter_Resize_U0->ap_clk(ap_clk);
    image_filter_Resize_U0->ap_rst(ap_rst_n_inv);
    image_filter_Resize_U0->ap_start(image_filter_Resize_U0_ap_start);
    image_filter_Resize_U0->ap_done(image_filter_Resize_U0_ap_done);
    image_filter_Resize_U0->ap_continue(image_filter_Resize_U0_ap_continue);
    image_filter_Resize_U0->ap_idle(image_filter_Resize_U0_ap_idle);
    image_filter_Resize_U0->ap_ready(image_filter_Resize_U0_ap_ready);
    image_filter_Resize_U0->rows(image_filter_Resize_U0_rows);
    image_filter_Resize_U0->cols(image_filter_Resize_U0_cols);
    image_filter_Resize_U0->p_src_data_stream_V_dout(image_filter_Resize_U0_p_src_data_stream_V_dout);
    image_filter_Resize_U0->p_src_data_stream_V_empty_n(image_filter_Resize_U0_p_src_data_stream_V_empty_n);
    image_filter_Resize_U0->p_src_data_stream_V_read(image_filter_Resize_U0_p_src_data_stream_V_read);
    image_filter_Resize_U0->p_dst_data_stream_V_din(image_filter_Resize_U0_p_dst_data_stream_V_din);
    image_filter_Resize_U0->p_dst_data_stream_V_full_n(image_filter_Resize_U0_p_dst_data_stream_V_full_n);
    image_filter_Resize_U0->p_dst_data_stream_V_write(image_filter_Resize_U0_p_dst_data_stream_V_write);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0 = new image_filter_Mat2AXIvideo_8_1080_1920_0_s("image_filter_Mat2AXIvideo_8_1080_1920_0_U0");
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_clk(ap_clk);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_rst(ap_rst_n_inv);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_start(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_done(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_continue(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_idle(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->ap_ready(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_ready);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->rows(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->cols(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->img_data_stream_V_dout(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->img_data_stream_V_empty_n(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->img_data_stream_V_read(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TDATA(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TVALID(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TREADY(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TKEEP(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TSTRB(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TUSER(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TLAST(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TID(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID);
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0->OUTPUT_STREAM_TDEST(image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST);
    img_0_data_stream_0_V_U = new FIFO_image_filter_img_0_data_stream_0_V("img_0_data_stream_0_V_U");
    img_0_data_stream_0_V_U->clk(ap_clk);
    img_0_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_V_U->if_read_ce(img_0_data_stream_0_V_U_ap_dummy_ce);
    img_0_data_stream_0_V_U->if_write_ce(img_0_data_stream_0_V_U_ap_dummy_ce);
    img_0_data_stream_0_V_U->if_din(img_0_data_stream_0_V_din);
    img_0_data_stream_0_V_U->if_full_n(img_0_data_stream_0_V_full_n);
    img_0_data_stream_0_V_U->if_write(img_0_data_stream_0_V_write);
    img_0_data_stream_0_V_U->if_dout(img_0_data_stream_0_V_dout);
    img_0_data_stream_0_V_U->if_empty_n(img_0_data_stream_0_V_empty_n);
    img_0_data_stream_0_V_U->if_read(img_0_data_stream_0_V_read);
    img_0_data_stream_1_V_U = new FIFO_image_filter_img_0_data_stream_1_V("img_0_data_stream_1_V_U");
    img_0_data_stream_1_V_U->clk(ap_clk);
    img_0_data_stream_1_V_U->reset(ap_rst_n_inv);
    img_0_data_stream_1_V_U->if_read_ce(img_0_data_stream_1_V_U_ap_dummy_ce);
    img_0_data_stream_1_V_U->if_write_ce(img_0_data_stream_1_V_U_ap_dummy_ce);
    img_0_data_stream_1_V_U->if_din(img_0_data_stream_1_V_din);
    img_0_data_stream_1_V_U->if_full_n(img_0_data_stream_1_V_full_n);
    img_0_data_stream_1_V_U->if_write(img_0_data_stream_1_V_write);
    img_0_data_stream_1_V_U->if_dout(img_0_data_stream_1_V_dout);
    img_0_data_stream_1_V_U->if_empty_n(img_0_data_stream_1_V_empty_n);
    img_0_data_stream_1_V_U->if_read(img_0_data_stream_1_V_read);
    img_0_data_stream_2_V_U = new FIFO_image_filter_img_0_data_stream_2_V("img_0_data_stream_2_V_U");
    img_0_data_stream_2_V_U->clk(ap_clk);
    img_0_data_stream_2_V_U->reset(ap_rst_n_inv);
    img_0_data_stream_2_V_U->if_read_ce(img_0_data_stream_2_V_U_ap_dummy_ce);
    img_0_data_stream_2_V_U->if_write_ce(img_0_data_stream_2_V_U_ap_dummy_ce);
    img_0_data_stream_2_V_U->if_din(img_0_data_stream_2_V_din);
    img_0_data_stream_2_V_U->if_full_n(img_0_data_stream_2_V_full_n);
    img_0_data_stream_2_V_U->if_write(img_0_data_stream_2_V_write);
    img_0_data_stream_2_V_U->if_dout(img_0_data_stream_2_V_dout);
    img_0_data_stream_2_V_U->if_empty_n(img_0_data_stream_2_V_empty_n);
    img_0_data_stream_2_V_U->if_read(img_0_data_stream_2_V_read);
    img_1_data_stream_0_V_U = new FIFO_image_filter_img_1_data_stream_0_V("img_1_data_stream_0_V_U");
    img_1_data_stream_0_V_U->clk(ap_clk);
    img_1_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_V_U->if_read_ce(img_1_data_stream_0_V_U_ap_dummy_ce);
    img_1_data_stream_0_V_U->if_write_ce(img_1_data_stream_0_V_U_ap_dummy_ce);
    img_1_data_stream_0_V_U->if_din(img_1_data_stream_0_V_din);
    img_1_data_stream_0_V_U->if_full_n(img_1_data_stream_0_V_full_n);
    img_1_data_stream_0_V_U->if_write(img_1_data_stream_0_V_write);
    img_1_data_stream_0_V_U->if_dout(img_1_data_stream_0_V_dout);
    img_1_data_stream_0_V_U->if_empty_n(img_1_data_stream_0_V_empty_n);
    img_1_data_stream_0_V_U->if_read(img_1_data_stream_0_V_read);
    img_2_data_stream_0_V_U = new FIFO_image_filter_img_2_data_stream_0_V("img_2_data_stream_0_V_U");
    img_2_data_stream_0_V_U->clk(ap_clk);
    img_2_data_stream_0_V_U->reset(ap_rst_n_inv);
    img_2_data_stream_0_V_U->if_read_ce(img_2_data_stream_0_V_U_ap_dummy_ce);
    img_2_data_stream_0_V_U->if_write_ce(img_2_data_stream_0_V_U_ap_dummy_ce);
    img_2_data_stream_0_V_U->if_din(img_2_data_stream_0_V_din);
    img_2_data_stream_0_V_U->if_full_n(img_2_data_stream_0_V_full_n);
    img_2_data_stream_0_V_U->if_write(img_2_data_stream_0_V_write);
    img_2_data_stream_0_V_U->if_dout(img_2_data_stream_0_V_dout);
    img_2_data_stream_0_V_U->if_empty_n(img_2_data_stream_0_V_empty_n);
    img_2_data_stream_0_V_U->if_read(img_2_data_stream_0_V_read);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY );

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_idle );
    sensitive << ( image_filter_CvtColor_U0_ap_idle );
    sensitive << ( image_filter_Resize_U0_ap_idle );
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_top_allready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done );

    SC_METHOD(thread_ap_sig_top_allready);
    sensitive << ( image_filter_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA);
    sensitive << ( INPUT_STREAM_TDATA );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST);
    sensitive << ( INPUT_STREAM_TDEST );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID);
    sensitive << ( INPUT_STREAM_TID );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP);
    sensitive << ( INPUT_STREAM_TKEEP );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST);
    sensitive << ( INPUT_STREAM_TLAST );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB);
    sensitive << ( INPUT_STREAM_TSTRB );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER);
    sensitive << ( INPUT_STREAM_TUSER );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID);
    sensitive << ( INPUT_STREAM_TVALID );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n);
    sensitive << ( img_0_data_stream_0_V_full_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n);
    sensitive << ( img_0_data_stream_1_V_full_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n);
    sensitive << ( img_0_data_stream_2_V_full_n );

    SC_METHOD(thread_image_filter_AXIvideo2Mat_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_CvtColor_U0_ap_continue);

    SC_METHOD(thread_image_filter_CvtColor_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_CvtColor_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_dst_data_stream_V_full_n);
    sensitive << ( img_1_data_stream_0_V_full_n );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_src_data_stream_0_V_dout);
    sensitive << ( img_0_data_stream_0_V_dout );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n);
    sensitive << ( img_0_data_stream_0_V_empty_n );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_src_data_stream_1_V_dout);
    sensitive << ( img_0_data_stream_1_V_dout );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n);
    sensitive << ( img_0_data_stream_1_V_empty_n );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_src_data_stream_2_V_dout);
    sensitive << ( img_0_data_stream_2_V_dout );

    SC_METHOD(thread_image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n);
    sensitive << ( img_0_data_stream_2_V_empty_n );

    SC_METHOD(thread_image_filter_CvtColor_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY);
    sensitive << ( OUTPUT_STREAM_TREADY );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue);
    sensitive << ( ap_sig_hs_continue );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout);
    sensitive << ( img_2_data_stream_0_V_dout );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n);
    sensitive << ( img_2_data_stream_0_V_empty_n );

    SC_METHOD(thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_image_filter_Resize_U0_ap_continue);

    SC_METHOD(thread_image_filter_Resize_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_image_filter_Resize_U0_cols);
    sensitive << ( cols );

    SC_METHOD(thread_image_filter_Resize_U0_p_dst_data_stream_V_full_n);
    sensitive << ( img_2_data_stream_0_V_full_n );

    SC_METHOD(thread_image_filter_Resize_U0_p_src_data_stream_V_dout);
    sensitive << ( img_1_data_stream_0_V_dout );

    SC_METHOD(thread_image_filter_Resize_U0_p_src_data_stream_V_empty_n);
    sensitive << ( img_1_data_stream_0_V_empty_n );

    SC_METHOD(thread_image_filter_Resize_U0_rows);
    sensitive << ( rows );

    SC_METHOD(thread_img_0_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_data_stream_0_V_din);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din );

    SC_METHOD(thread_img_0_data_stream_0_V_read);
    sensitive << ( image_filter_CvtColor_U0_p_src_data_stream_0_V_read );

    SC_METHOD(thread_img_0_data_stream_0_V_write);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write );

    SC_METHOD(thread_img_0_data_stream_1_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_data_stream_1_V_din);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din );

    SC_METHOD(thread_img_0_data_stream_1_V_read);
    sensitive << ( image_filter_CvtColor_U0_p_src_data_stream_1_V_read );

    SC_METHOD(thread_img_0_data_stream_1_V_write);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write );

    SC_METHOD(thread_img_0_data_stream_2_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_0_data_stream_2_V_din);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din );

    SC_METHOD(thread_img_0_data_stream_2_V_read);
    sensitive << ( image_filter_CvtColor_U0_p_src_data_stream_2_V_read );

    SC_METHOD(thread_img_0_data_stream_2_V_write);
    sensitive << ( image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write );

    SC_METHOD(thread_img_1_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_1_data_stream_0_V_din);
    sensitive << ( image_filter_CvtColor_U0_p_dst_data_stream_V_din );

    SC_METHOD(thread_img_1_data_stream_0_V_read);
    sensitive << ( image_filter_Resize_U0_p_src_data_stream_V_read );

    SC_METHOD(thread_img_1_data_stream_0_V_write);
    sensitive << ( image_filter_CvtColor_U0_p_dst_data_stream_V_write );

    SC_METHOD(thread_img_2_data_stream_0_V_U_ap_dummy_ce);

    SC_METHOD(thread_img_2_data_stream_0_V_din);
    sensitive << ( image_filter_Resize_U0_p_dst_data_stream_V_din );

    SC_METHOD(thread_img_2_data_stream_0_V_read);
    sensitive << ( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read );

    SC_METHOD(thread_img_2_data_stream_0_V_write);
    sensitive << ( image_filter_Resize_U0_p_dst_data_stream_V_write );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = SC_LOGIC_0;
    ap_reg_procdone_image_filter_CvtColor_U0 = SC_LOGIC_0;
    ap_reg_procdone_image_filter_Resize_U0 = SC_LOGIC_0;
    ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "image_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, rows, "(port)rows");
    sc_trace(mVcdFile, cols, "(port)cols");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_start, "image_filter_AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_done, "image_filter_AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_continue, "image_filter_AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_idle, "image_filter_AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_ap_ready, "image_filter_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST, "image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_rows, "image_filter_AXIvideo2Mat_U0_rows");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_cols, "image_filter_AXIvideo2Mat_U0_cols");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din, "image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n, "image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write, "image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din, "image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n, "image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write, "image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din, "image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n, "image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n");
    sc_trace(mVcdFile, image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write, "image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_ap_start, "image_filter_CvtColor_U0_ap_start");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_ap_done, "image_filter_CvtColor_U0_ap_done");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_ap_continue, "image_filter_CvtColor_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_ap_idle, "image_filter_CvtColor_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_ap_ready, "image_filter_CvtColor_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_rows, "image_filter_CvtColor_U0_rows");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_cols, "image_filter_CvtColor_U0_cols");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_0_V_dout, "image_filter_CvtColor_U0_p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n, "image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_0_V_read, "image_filter_CvtColor_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_1_V_dout, "image_filter_CvtColor_U0_p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n, "image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_1_V_read, "image_filter_CvtColor_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_2_V_dout, "image_filter_CvtColor_U0_p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n, "image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_src_data_stream_2_V_read, "image_filter_CvtColor_U0_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_dst_data_stream_V_din, "image_filter_CvtColor_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_dst_data_stream_V_full_n, "image_filter_CvtColor_U0_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, image_filter_CvtColor_U0_p_dst_data_stream_V_write, "image_filter_CvtColor_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Resize_U0_ap_start, "image_filter_Resize_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Resize_U0_ap_done, "image_filter_Resize_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Resize_U0_ap_continue, "image_filter_Resize_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Resize_U0_ap_idle, "image_filter_Resize_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Resize_U0_ap_ready, "image_filter_Resize_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Resize_U0_rows, "image_filter_Resize_U0_rows");
    sc_trace(mVcdFile, image_filter_Resize_U0_cols, "image_filter_Resize_U0_cols");
    sc_trace(mVcdFile, image_filter_Resize_U0_p_src_data_stream_V_dout, "image_filter_Resize_U0_p_src_data_stream_V_dout");
    sc_trace(mVcdFile, image_filter_Resize_U0_p_src_data_stream_V_empty_n, "image_filter_Resize_U0_p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, image_filter_Resize_U0_p_src_data_stream_V_read, "image_filter_Resize_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_Resize_U0_p_dst_data_stream_V_din, "image_filter_Resize_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, image_filter_Resize_U0_p_dst_data_stream_V_full_n, "image_filter_Resize_U0_p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, image_filter_Resize_U0_p_dst_data_stream_V_write, "image_filter_Resize_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_ready, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_ready");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST, "image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, img_0_data_stream_0_V_U_ap_dummy_ce, "img_0_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_data_stream_0_V_din, "img_0_data_stream_0_V_din");
    sc_trace(mVcdFile, img_0_data_stream_0_V_full_n, "img_0_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_write, "img_0_data_stream_0_V_write");
    sc_trace(mVcdFile, img_0_data_stream_0_V_dout, "img_0_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_V_empty_n, "img_0_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_V_read, "img_0_data_stream_0_V_read");
    sc_trace(mVcdFile, img_0_data_stream_1_V_U_ap_dummy_ce, "img_0_data_stream_1_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_data_stream_1_V_din, "img_0_data_stream_1_V_din");
    sc_trace(mVcdFile, img_0_data_stream_1_V_full_n, "img_0_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_V_write, "img_0_data_stream_1_V_write");
    sc_trace(mVcdFile, img_0_data_stream_1_V_dout, "img_0_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_V_empty_n, "img_0_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_V_read, "img_0_data_stream_1_V_read");
    sc_trace(mVcdFile, img_0_data_stream_2_V_U_ap_dummy_ce, "img_0_data_stream_2_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_0_data_stream_2_V_din, "img_0_data_stream_2_V_din");
    sc_trace(mVcdFile, img_0_data_stream_2_V_full_n, "img_0_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_V_write, "img_0_data_stream_2_V_write");
    sc_trace(mVcdFile, img_0_data_stream_2_V_dout, "img_0_data_stream_2_V_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_V_empty_n, "img_0_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_V_read, "img_0_data_stream_2_V_read");
    sc_trace(mVcdFile, img_1_data_stream_0_V_U_ap_dummy_ce, "img_1_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_1_data_stream_0_V_din, "img_1_data_stream_0_V_din");
    sc_trace(mVcdFile, img_1_data_stream_0_V_full_n, "img_1_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_write, "img_1_data_stream_0_V_write");
    sc_trace(mVcdFile, img_1_data_stream_0_V_dout, "img_1_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_V_empty_n, "img_1_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_V_read, "img_1_data_stream_0_V_read");
    sc_trace(mVcdFile, img_2_data_stream_0_V_U_ap_dummy_ce, "img_2_data_stream_0_V_U_ap_dummy_ce");
    sc_trace(mVcdFile, img_2_data_stream_0_V_din, "img_2_data_stream_0_V_din");
    sc_trace(mVcdFile, img_2_data_stream_0_V_full_n, "img_2_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_2_data_stream_0_V_write, "img_2_data_stream_0_V_write");
    sc_trace(mVcdFile, img_2_data_stream_0_V_dout, "img_2_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_2_data_stream_0_V_empty_n, "img_2_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_2_data_stream_0_V_read, "img_2_data_stream_0_V_read");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_AXIvideo2Mat_U0, "ap_reg_procdone_image_filter_AXIvideo2Mat_U0");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_CvtColor_U0, "ap_reg_procdone_image_filter_CvtColor_U0");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_Resize_U0, "ap_reg_procdone_image_filter_Resize_U0");
    sc_trace(mVcdFile, ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0, "ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0");
    sc_trace(mVcdFile, ap_CS, "ap_CS");
    sc_trace(mVcdFile, ap_sig_top_allready, "ap_sig_top_allready");
#endif

    }
    mHdltvinHandle.open("image_filter.hdltvin.dat");
    mHdltvoutHandle.open("image_filter.hdltvout.dat");
}

image_filter::~image_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete image_filter_AXIvideo2Mat_U0;
    delete image_filter_CvtColor_U0;
    delete image_filter_Resize_U0;
    delete image_filter_Mat2AXIvideo_8_1080_1920_0_U0;
    delete img_0_data_stream_0_V_U;
    delete img_0_data_stream_1_V_U;
    delete img_0_data_stream_2_V_U;
    delete img_1_data_stream_0_V_U;
    delete img_2_data_stream_0_V_U;
}

void image_filter::thread_ap_clk_no_reset_() {
    ap_CS = ap_const_logic_0;
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(image_filter_AXIvideo2Mat_U0_ap_done.read(), ap_const_logic_1)) {
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_CvtColor_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_CvtColor_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_CvtColor_U0_ap_done.read())) {
            ap_reg_procdone_image_filter_CvtColor_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done.read())) {
            ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_procdone_image_filter_Resize_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_image_filter_Resize_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Resize_U0_ap_done.read())) {
            ap_reg_procdone_image_filter_Resize_U0 = ap_const_logic_1;
        }
    }
}

void image_filter::thread_INPUT_STREAM_TREADY() {
    INPUT_STREAM_TREADY = image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY.read();
}

void image_filter::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA.read();
}

void image_filter::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST.read();
}

void image_filter::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID.read();
}

void image_filter::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP.read();
}

void image_filter::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST.read();
}

void image_filter::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB.read();
}

void image_filter::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER.read();
}

void image_filter::thread_OUTPUT_STREAM_TVALID() {
    OUTPUT_STREAM_TVALID = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID.read();
}

void image_filter::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void image_filter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(image_filter_AXIvideo2Mat_U0_ap_idle.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_CvtColor_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Resize_U0_ap_idle.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void image_filter::thread_ap_ready() {
    ap_ready = ap_sig_top_allready.read();
}

void image_filter::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void image_filter::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void image_filter::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done.read())) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void image_filter::thread_ap_sig_top_allready() {
    ap_sig_top_allready = image_filter_AXIvideo2Mat_U0_ap_ready.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA = INPUT_STREAM_TDATA.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST = INPUT_STREAM_TDEST.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID = INPUT_STREAM_TID.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP = INPUT_STREAM_TKEEP.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST = INPUT_STREAM_TLAST.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB = INPUT_STREAM_TSTRB.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER = INPUT_STREAM_TUSER.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID() {
    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID = INPUT_STREAM_TVALID.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_ap_continue() {
    image_filter_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_ap_start() {
    image_filter_AXIvideo2Mat_U0_ap_start = (ap_start.read());
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_cols() {
    image_filter_AXIvideo2Mat_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n() {
    image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n = img_0_data_stream_0_V_full_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n() {
    image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n = img_0_data_stream_1_V_full_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n() {
    image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n = img_0_data_stream_2_V_full_n.read();
}

void image_filter::thread_image_filter_AXIvideo2Mat_U0_rows() {
    image_filter_AXIvideo2Mat_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_CvtColor_U0_ap_continue() {
    image_filter_CvtColor_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_CvtColor_U0_ap_start() {
    image_filter_CvtColor_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_CvtColor_U0_cols() {
    image_filter_CvtColor_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_CvtColor_U0_p_dst_data_stream_V_full_n() {
    image_filter_CvtColor_U0_p_dst_data_stream_V_full_n = img_1_data_stream_0_V_full_n.read();
}

void image_filter::thread_image_filter_CvtColor_U0_p_src_data_stream_0_V_dout() {
    image_filter_CvtColor_U0_p_src_data_stream_0_V_dout = img_0_data_stream_0_V_dout.read();
}

void image_filter::thread_image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n() {
    image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n = img_0_data_stream_0_V_empty_n.read();
}

void image_filter::thread_image_filter_CvtColor_U0_p_src_data_stream_1_V_dout() {
    image_filter_CvtColor_U0_p_src_data_stream_1_V_dout = img_0_data_stream_1_V_dout.read();
}

void image_filter::thread_image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n() {
    image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n = img_0_data_stream_1_V_empty_n.read();
}

void image_filter::thread_image_filter_CvtColor_U0_p_src_data_stream_2_V_dout() {
    image_filter_CvtColor_U0_p_src_data_stream_2_V_dout = img_0_data_stream_2_V_dout.read();
}

void image_filter::thread_image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n() {
    image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n = img_0_data_stream_2_V_empty_n.read();
}

void image_filter::thread_image_filter_CvtColor_U0_rows() {
    image_filter_CvtColor_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue = ap_sig_hs_continue.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout = img_2_data_stream_0_V_dout.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n = img_2_data_stream_0_V_empty_n.read();
}

void image_filter::thread_image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows() {
    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_image_filter_Resize_U0_ap_continue() {
    image_filter_Resize_U0_ap_continue = ap_const_logic_1;
}

void image_filter::thread_image_filter_Resize_U0_ap_start() {
    image_filter_Resize_U0_ap_start = ap_start.read();
}

void image_filter::thread_image_filter_Resize_U0_cols() {
    image_filter_Resize_U0_cols = cols.read().range(11, 0);
}

void image_filter::thread_image_filter_Resize_U0_p_dst_data_stream_V_full_n() {
    image_filter_Resize_U0_p_dst_data_stream_V_full_n = img_2_data_stream_0_V_full_n.read();
}

void image_filter::thread_image_filter_Resize_U0_p_src_data_stream_V_dout() {
    image_filter_Resize_U0_p_src_data_stream_V_dout = img_1_data_stream_0_V_dout.read();
}

void image_filter::thread_image_filter_Resize_U0_p_src_data_stream_V_empty_n() {
    image_filter_Resize_U0_p_src_data_stream_V_empty_n = img_1_data_stream_0_V_empty_n.read();
}

void image_filter::thread_image_filter_Resize_U0_rows() {
    image_filter_Resize_U0_rows = rows.read().range(11, 0);
}

void image_filter::thread_img_0_data_stream_0_V_U_ap_dummy_ce() {
    img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_0_data_stream_0_V_din() {
    img_0_data_stream_0_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din.read();
}

void image_filter::thread_img_0_data_stream_0_V_read() {
    img_0_data_stream_0_V_read = image_filter_CvtColor_U0_p_src_data_stream_0_V_read.read();
}

void image_filter::thread_img_0_data_stream_0_V_write() {
    img_0_data_stream_0_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write.read();
}

void image_filter::thread_img_0_data_stream_1_V_U_ap_dummy_ce() {
    img_0_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_0_data_stream_1_V_din() {
    img_0_data_stream_1_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din.read();
}

void image_filter::thread_img_0_data_stream_1_V_read() {
    img_0_data_stream_1_V_read = image_filter_CvtColor_U0_p_src_data_stream_1_V_read.read();
}

void image_filter::thread_img_0_data_stream_1_V_write() {
    img_0_data_stream_1_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write.read();
}

void image_filter::thread_img_0_data_stream_2_V_U_ap_dummy_ce() {
    img_0_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_0_data_stream_2_V_din() {
    img_0_data_stream_2_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din.read();
}

void image_filter::thread_img_0_data_stream_2_V_read() {
    img_0_data_stream_2_V_read = image_filter_CvtColor_U0_p_src_data_stream_2_V_read.read();
}

void image_filter::thread_img_0_data_stream_2_V_write() {
    img_0_data_stream_2_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write.read();
}

void image_filter::thread_img_1_data_stream_0_V_U_ap_dummy_ce() {
    img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_1_data_stream_0_V_din() {
    img_1_data_stream_0_V_din = image_filter_CvtColor_U0_p_dst_data_stream_V_din.read();
}

void image_filter::thread_img_1_data_stream_0_V_read() {
    img_1_data_stream_0_V_read = image_filter_Resize_U0_p_src_data_stream_V_read.read();
}

void image_filter::thread_img_1_data_stream_0_V_write() {
    img_1_data_stream_0_V_write = image_filter_CvtColor_U0_p_dst_data_stream_V_write.read();
}

void image_filter::thread_img_2_data_stream_0_V_U_ap_dummy_ce() {
    img_2_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;
}

void image_filter::thread_img_2_data_stream_0_V_din() {
    img_2_data_stream_0_V_din = image_filter_Resize_U0_p_dst_data_stream_V_din.read();
}

void image_filter::thread_img_2_data_stream_0_V_read() {
    img_2_data_stream_0_V_read = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read.read();
}

void image_filter::thread_img_2_data_stream_0_V_write() {
    img_2_data_stream_0_V_write = image_filter_Resize_U0_p_dst_data_stream_V_write.read();
}

void image_filter::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"INPUT_STREAM_TDATA\" :  \"" << INPUT_STREAM_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TKEEP\" :  \"" << INPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TSTRB\" :  \"" << INPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TUSER\" :  \"" << INPUT_STREAM_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TLAST\" :  \"" << INPUT_STREAM_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TID\" :  \"" << INPUT_STREAM_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDEST\" :  \"" << INPUT_STREAM_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"OUTPUT_STREAM_TDATA\" :  \"" << OUTPUT_STREAM_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TKEEP\" :  \"" << OUTPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TSTRB\" :  \"" << OUTPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TUSER\" :  \"" << OUTPUT_STREAM_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TLAST\" :  \"" << OUTPUT_STREAM_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TID\" :  \"" << OUTPUT_STREAM_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDEST\" :  \"" << OUTPUT_STREAM_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rows\" :  \"" << rows.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"cols\" :  \"" << cols.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TVALID\" :  \"" << INPUT_STREAM_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"INPUT_STREAM_TREADY\" :  \"" << INPUT_STREAM_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TVALID\" :  \"" << OUTPUT_STREAM_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_STREAM_TREADY\" :  \"" << OUTPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

