// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _image_filter_Mat2AXIvideo_8_1080_1920_0_s_HH_
#define _image_filter_Mat2AXIvideo_8_1080_1920_0_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct image_filter_Mat2AXIvideo_8_1080_1920_0_s : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<11> > rows;
    sc_in< sc_lv<11> > cols;
    sc_in< sc_lv<8> > img_data_stream_V_dout;
    sc_in< sc_logic > img_data_stream_V_empty_n;
    sc_out< sc_logic > img_data_stream_V_read;
    sc_out< sc_lv<8> > OUTPUT_STREAM_TDATA;
    sc_out< sc_logic > OUTPUT_STREAM_TVALID;
    sc_in< sc_logic > OUTPUT_STREAM_TREADY;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TKEEP;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TSTRB;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TUSER;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TLAST;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TID;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TDEST;


    // Module declarations
    image_filter_Mat2AXIvideo_8_1080_1920_0_s(sc_module_name name);
    SC_HAS_PROCESS(image_filter_Mat2AXIvideo_8_1080_1920_0_s);

    ~image_filter_Mat2AXIvideo_8_1080_1920_0_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_lv<11> > p_1_i_reg_151;
    sc_signal< bool > ap_sig_bdd_52;
    sc_signal< sc_lv<11> > r_V_fu_162_p2;
    sc_signal< sc_lv<1> > exitcond7_i_fu_173_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_66;
    sc_signal< sc_lv<11> > i_V_fu_178_p2;
    sc_signal< sc_lv<11> > i_V_reg_235;
    sc_signal< sc_lv<1> > exitcond_i_fu_184_p2;
    sc_signal< sc_lv<1> > exitcond_i_reg_240;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_77;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_85;
    sc_signal< sc_logic > ap_sig_ioackin_OUTPUT_STREAM_TREADY;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<11> > j_V_fu_189_p2;
    sc_signal< sc_lv<1> > axi_last_V_fu_195_p2;
    sc_signal< sc_lv<1> > axi_last_V_reg_249;
    sc_signal< sc_lv<11> > p_i_reg_140;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_3;
    sc_signal< bool > ap_sig_bdd_116;
    sc_signal< sc_lv<1> > tmp_user_V_fu_88;
    sc_signal< sc_logic > ap_reg_ioackin_OUTPUT_STREAM_TREADY;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_st1_fsm_0;
    static const sc_lv<4> ap_ST_st2_fsm_1;
    static const sc_lv<4> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<4> ap_ST_st5_fsm_3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<11> ap_const_lv11_7FF;
    static const sc_lv<11> ap_const_lv11_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_OUTPUT_STREAM_TDATA();
    void thread_OUTPUT_STREAM_TDEST();
    void thread_OUTPUT_STREAM_TID();
    void thread_OUTPUT_STREAM_TKEEP();
    void thread_OUTPUT_STREAM_TLAST();
    void thread_OUTPUT_STREAM_TSTRB();
    void thread_OUTPUT_STREAM_TUSER();
    void thread_OUTPUT_STREAM_TVALID();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_116();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_52();
    void thread_ap_sig_bdd_66();
    void thread_ap_sig_bdd_77();
    void thread_ap_sig_bdd_85();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st5_fsm_3();
    void thread_ap_sig_ioackin_OUTPUT_STREAM_TREADY();
    void thread_axi_last_V_fu_195_p2();
    void thread_exitcond7_i_fu_173_p2();
    void thread_exitcond_i_fu_184_p2();
    void thread_i_V_fu_178_p2();
    void thread_img_data_stream_V_read();
    void thread_j_V_fu_189_p2();
    void thread_r_V_fu_162_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
