// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_filter,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=11.120000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=2,HLS_SYN_DSP=19,HLS_SYN_FF=5372,HLS_SYN_LUT=5523}" *)

module image_filter (
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        rows,
        cols,
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        ap_start,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY,
        ap_done,
        ap_idle,
        ap_ready
);

parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;

input  [31:0] INPUT_STREAM_TDATA;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
output  [7:0] OUTPUT_STREAM_TDATA;
output  [0:0] OUTPUT_STREAM_TKEEP;
output  [0:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [0:0] OUTPUT_STREAM_TID;
output  [0:0] OUTPUT_STREAM_TDEST;
input  [31:0] rows;
input  [31:0] cols;
input   ap_clk;
input   ap_rst_n;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input   ap_start;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;
output   ap_done;
output   ap_idle;
output   ap_ready;

reg ap_idle;
reg    ap_rst_n_inv;
wire    image_filter_AXIvideo2Mat_U0_ap_start;
wire    image_filter_AXIvideo2Mat_U0_ap_done;
wire    image_filter_AXIvideo2Mat_U0_ap_continue;
wire    image_filter_AXIvideo2Mat_U0_ap_idle;
wire    image_filter_AXIvideo2Mat_U0_ap_ready;
wire   [31:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA;
wire    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID;
wire    image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
wire   [3:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP;
wire   [3:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB;
wire   [0:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER;
wire   [0:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST;
wire   [0:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID;
wire   [0:0] image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST;
wire   [10:0] image_filter_AXIvideo2Mat_U0_rows;
wire   [10:0] image_filter_AXIvideo2Mat_U0_cols;
wire   [7:0] image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n;
wire    image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire    image_filter_CvtColor_U0_ap_start;
wire    image_filter_CvtColor_U0_ap_done;
wire    image_filter_CvtColor_U0_ap_continue;
wire    image_filter_CvtColor_U0_ap_idle;
wire    image_filter_CvtColor_U0_ap_ready;
wire   [10:0] image_filter_CvtColor_U0_rows;
wire   [10:0] image_filter_CvtColor_U0_cols;
wire   [7:0] image_filter_CvtColor_U0_p_src_data_stream_0_V_dout;
wire    image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n;
wire    image_filter_CvtColor_U0_p_src_data_stream_0_V_read;
wire   [7:0] image_filter_CvtColor_U0_p_src_data_stream_1_V_dout;
wire    image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n;
wire    image_filter_CvtColor_U0_p_src_data_stream_1_V_read;
wire   [7:0] image_filter_CvtColor_U0_p_src_data_stream_2_V_dout;
wire    image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n;
wire    image_filter_CvtColor_U0_p_src_data_stream_2_V_read;
wire   [7:0] image_filter_CvtColor_U0_p_dst_data_stream_V_din;
wire    image_filter_CvtColor_U0_p_dst_data_stream_V_full_n;
wire    image_filter_CvtColor_U0_p_dst_data_stream_V_write;
wire    image_filter_Resize_U0_ap_start;
wire    image_filter_Resize_U0_ap_done;
wire    image_filter_Resize_U0_ap_continue;
wire    image_filter_Resize_U0_ap_idle;
wire    image_filter_Resize_U0_ap_ready;
wire   [10:0] image_filter_Resize_U0_rows;
wire   [10:0] image_filter_Resize_U0_cols;
wire   [7:0] image_filter_Resize_U0_p_src_data_stream_V_dout;
wire    image_filter_Resize_U0_p_src_data_stream_V_empty_n;
wire    image_filter_Resize_U0_p_src_data_stream_V_read;
wire   [7:0] image_filter_Resize_U0_p_dst_data_stream_V_din;
wire    image_filter_Resize_U0_p_dst_data_stream_V_full_n;
wire    image_filter_Resize_U0_p_dst_data_stream_V_write;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_ready;
wire   [10:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows;
wire   [10:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols;
wire   [7:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read;
wire   [7:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID;
wire    image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY;
wire   [0:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP;
wire   [0:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB;
wire   [0:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER;
wire   [0:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST;
wire   [0:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID;
wire   [0:0] image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST;
wire    ap_sig_hs_continue;
wire    img_0_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_0_V_din;
wire    img_0_data_stream_0_V_full_n;
wire    img_0_data_stream_0_V_write;
wire   [7:0] img_0_data_stream_0_V_dout;
wire    img_0_data_stream_0_V_empty_n;
wire    img_0_data_stream_0_V_read;
wire    img_0_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_1_V_din;
wire    img_0_data_stream_1_V_full_n;
wire    img_0_data_stream_1_V_write;
wire   [7:0] img_0_data_stream_1_V_dout;
wire    img_0_data_stream_1_V_empty_n;
wire    img_0_data_stream_1_V_read;
wire    img_0_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_0_data_stream_2_V_din;
wire    img_0_data_stream_2_V_full_n;
wire    img_0_data_stream_2_V_write;
wire   [7:0] img_0_data_stream_2_V_dout;
wire    img_0_data_stream_2_V_empty_n;
wire    img_0_data_stream_2_V_read;
wire    img_1_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_1_data_stream_0_V_din;
wire    img_1_data_stream_0_V_full_n;
wire    img_1_data_stream_0_V_write;
wire   [7:0] img_1_data_stream_0_V_dout;
wire    img_1_data_stream_0_V_empty_n;
wire    img_1_data_stream_0_V_read;
wire    img_2_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_2_data_stream_0_V_din;
wire    img_2_data_stream_0_V_full_n;
wire    img_2_data_stream_0_V_write;
wire   [7:0] img_2_data_stream_0_V_dout;
wire    img_2_data_stream_0_V_empty_n;
wire    img_2_data_stream_0_V_read;
reg    ap_reg_procdone_image_filter_AXIvideo2Mat_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_image_filter_CvtColor_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_Resize_U0 = 1'b0;
reg    ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 = 1'b0;
reg    ap_CS;
wire    ap_sig_top_allready;


image_filter_AXIvideo2Mat image_filter_AXIvideo2Mat_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_AXIvideo2Mat_U0_ap_start ),
    .ap_done( image_filter_AXIvideo2Mat_U0_ap_done ),
    .ap_continue( image_filter_AXIvideo2Mat_U0_ap_continue ),
    .ap_idle( image_filter_AXIvideo2Mat_U0_ap_idle ),
    .ap_ready( image_filter_AXIvideo2Mat_U0_ap_ready ),
    .INPUT_STREAM_TDATA( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA ),
    .INPUT_STREAM_TVALID( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID ),
    .INPUT_STREAM_TREADY( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY ),
    .INPUT_STREAM_TKEEP( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP ),
    .INPUT_STREAM_TSTRB( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB ),
    .INPUT_STREAM_TUSER( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER ),
    .INPUT_STREAM_TLAST( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST ),
    .INPUT_STREAM_TID( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID ),
    .INPUT_STREAM_TDEST( image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST ),
    .rows( image_filter_AXIvideo2Mat_U0_rows ),
    .cols( image_filter_AXIvideo2Mat_U0_cols ),
    .img_data_stream_0_V_din( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din ),
    .img_data_stream_0_V_full_n( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n ),
    .img_data_stream_0_V_write( image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write ),
    .img_data_stream_1_V_din( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din ),
    .img_data_stream_1_V_full_n( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n ),
    .img_data_stream_1_V_write( image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write ),
    .img_data_stream_2_V_din( image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din ),
    .img_data_stream_2_V_full_n( image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n ),
    .img_data_stream_2_V_write( image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write )
);

image_filter_CvtColor image_filter_CvtColor_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_CvtColor_U0_ap_start ),
    .ap_done( image_filter_CvtColor_U0_ap_done ),
    .ap_continue( image_filter_CvtColor_U0_ap_continue ),
    .ap_idle( image_filter_CvtColor_U0_ap_idle ),
    .ap_ready( image_filter_CvtColor_U0_ap_ready ),
    .rows( image_filter_CvtColor_U0_rows ),
    .cols( image_filter_CvtColor_U0_cols ),
    .p_src_data_stream_0_V_dout( image_filter_CvtColor_U0_p_src_data_stream_0_V_dout ),
    .p_src_data_stream_0_V_empty_n( image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n ),
    .p_src_data_stream_0_V_read( image_filter_CvtColor_U0_p_src_data_stream_0_V_read ),
    .p_src_data_stream_1_V_dout( image_filter_CvtColor_U0_p_src_data_stream_1_V_dout ),
    .p_src_data_stream_1_V_empty_n( image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n ),
    .p_src_data_stream_1_V_read( image_filter_CvtColor_U0_p_src_data_stream_1_V_read ),
    .p_src_data_stream_2_V_dout( image_filter_CvtColor_U0_p_src_data_stream_2_V_dout ),
    .p_src_data_stream_2_V_empty_n( image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n ),
    .p_src_data_stream_2_V_read( image_filter_CvtColor_U0_p_src_data_stream_2_V_read ),
    .p_dst_data_stream_V_din( image_filter_CvtColor_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( image_filter_CvtColor_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( image_filter_CvtColor_U0_p_dst_data_stream_V_write )
);

image_filter_Resize image_filter_Resize_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Resize_U0_ap_start ),
    .ap_done( image_filter_Resize_U0_ap_done ),
    .ap_continue( image_filter_Resize_U0_ap_continue ),
    .ap_idle( image_filter_Resize_U0_ap_idle ),
    .ap_ready( image_filter_Resize_U0_ap_ready ),
    .rows( image_filter_Resize_U0_rows ),
    .cols( image_filter_Resize_U0_cols ),
    .p_src_data_stream_V_dout( image_filter_Resize_U0_p_src_data_stream_V_dout ),
    .p_src_data_stream_V_empty_n( image_filter_Resize_U0_p_src_data_stream_V_empty_n ),
    .p_src_data_stream_V_read( image_filter_Resize_U0_p_src_data_stream_V_read ),
    .p_dst_data_stream_V_din( image_filter_Resize_U0_p_dst_data_stream_V_din ),
    .p_dst_data_stream_V_full_n( image_filter_Resize_U0_p_dst_data_stream_V_full_n ),
    .p_dst_data_stream_V_write( image_filter_Resize_U0_p_dst_data_stream_V_write )
);

image_filter_Mat2AXIvideo_8_1080_1920_0_s image_filter_Mat2AXIvideo_8_1080_1920_0_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start ),
    .ap_done( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done ),
    .ap_continue( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue ),
    .ap_idle( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle ),
    .ap_ready( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_ready ),
    .rows( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows ),
    .cols( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols ),
    .img_data_stream_V_dout( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout ),
    .img_data_stream_V_empty_n( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n ),
    .img_data_stream_V_read( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read ),
    .OUTPUT_STREAM_TDATA( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA ),
    .OUTPUT_STREAM_TVALID( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID ),
    .OUTPUT_STREAM_TREADY( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY ),
    .OUTPUT_STREAM_TKEEP( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP ),
    .OUTPUT_STREAM_TSTRB( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB ),
    .OUTPUT_STREAM_TUSER( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER ),
    .OUTPUT_STREAM_TLAST( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST ),
    .OUTPUT_STREAM_TID( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID ),
    .OUTPUT_STREAM_TDEST( image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST )
);

FIFO_image_filter_img_0_data_stream_0_V img_0_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_0_V_din ),
    .if_full_n( img_0_data_stream_0_V_full_n ),
    .if_write( img_0_data_stream_0_V_write ),
    .if_dout( img_0_data_stream_0_V_dout ),
    .if_empty_n( img_0_data_stream_0_V_empty_n ),
    .if_read( img_0_data_stream_0_V_read )
);

FIFO_image_filter_img_0_data_stream_1_V img_0_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_1_V_din ),
    .if_full_n( img_0_data_stream_1_V_full_n ),
    .if_write( img_0_data_stream_1_V_write ),
    .if_dout( img_0_data_stream_1_V_dout ),
    .if_empty_n( img_0_data_stream_1_V_empty_n ),
    .if_read( img_0_data_stream_1_V_read )
);

FIFO_image_filter_img_0_data_stream_2_V img_0_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_0_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_0_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_0_data_stream_2_V_din ),
    .if_full_n( img_0_data_stream_2_V_full_n ),
    .if_write( img_0_data_stream_2_V_write ),
    .if_dout( img_0_data_stream_2_V_dout ),
    .if_empty_n( img_0_data_stream_2_V_empty_n ),
    .if_read( img_0_data_stream_2_V_read )
);

FIFO_image_filter_img_1_data_stream_0_V img_1_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_1_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_1_data_stream_0_V_din ),
    .if_full_n( img_1_data_stream_0_V_full_n ),
    .if_write( img_1_data_stream_0_V_write ),
    .if_dout( img_1_data_stream_0_V_dout ),
    .if_empty_n( img_1_data_stream_0_V_empty_n ),
    .if_read( img_1_data_stream_0_V_read )
);

FIFO_image_filter_img_2_data_stream_0_V img_2_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_2_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_2_data_stream_0_V_din ),
    .if_full_n( img_2_data_stream_0_V_full_n ),
    .if_write( img_2_data_stream_0_V_write ),
    .if_dout( img_2_data_stream_0_V_dout ),
    .if_empty_n( img_2_data_stream_0_V_empty_n ),
    .if_read( img_2_data_stream_0_V_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_image_filter_AXIvideo2Mat_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_0;
        end else if ((image_filter_AXIvideo2Mat_U0_ap_done == ap_const_logic_1)) begin
            ap_reg_procdone_image_filter_AXIvideo2Mat_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_image_filter_CvtColor_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_CvtColor_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_CvtColor_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_CvtColor_U0_ap_done)) begin
            ap_reg_procdone_image_filter_CvtColor_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Mat2AXIvideo_8_1080_1920_0_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_image_filter_Resize_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_image_filter_Resize_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_image_filter_Resize_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == image_filter_Resize_U0_ap_done)) begin
            ap_reg_procdone_image_filter_Resize_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (image_filter_AXIvideo2Mat_U0_ap_idle or image_filter_CvtColor_U0_ap_idle or image_filter_Resize_U0_ap_idle or image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle) begin
    if (((image_filter_AXIvideo2Mat_U0_ap_idle == ap_const_logic_1) & (ap_const_logic_1 == image_filter_CvtColor_U0_ap_idle) & (ap_const_logic_1 == image_filter_Resize_U0_ap_idle) & (ap_const_logic_1 == image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_idle))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done) begin
    if ((ap_const_logic_1 == image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

assign INPUT_STREAM_TREADY = image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TREADY;

assign OUTPUT_STREAM_TDATA = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDATA;

assign OUTPUT_STREAM_TDEST = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TDEST;

assign OUTPUT_STREAM_TID = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TID;

assign OUTPUT_STREAM_TKEEP = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TKEEP;

assign OUTPUT_STREAM_TLAST = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TLAST;

assign OUTPUT_STREAM_TSTRB = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TSTRB;

assign OUTPUT_STREAM_TUSER = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TUSER;

assign OUTPUT_STREAM_TVALID = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TVALID;

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_1;

assign ap_sig_top_allready = image_filter_AXIvideo2Mat_U0_ap_ready;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDATA = INPUT_STREAM_TDATA;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TDEST = INPUT_STREAM_TDEST;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TID = INPUT_STREAM_TID;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP = INPUT_STREAM_TKEEP;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TLAST = INPUT_STREAM_TLAST;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB = INPUT_STREAM_TSTRB;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TUSER = INPUT_STREAM_TUSER;

assign image_filter_AXIvideo2Mat_U0_INPUT_STREAM_TVALID = INPUT_STREAM_TVALID;

assign image_filter_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;

assign image_filter_AXIvideo2Mat_U0_ap_start = ap_start;

assign image_filter_AXIvideo2Mat_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_full_n = img_0_data_stream_0_V_full_n;

assign image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_full_n = img_0_data_stream_1_V_full_n;

assign image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_full_n = img_0_data_stream_2_V_full_n;

assign image_filter_AXIvideo2Mat_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_CvtColor_U0_ap_continue = ap_const_logic_1;

assign image_filter_CvtColor_U0_ap_start = ap_start;

assign image_filter_CvtColor_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_CvtColor_U0_p_dst_data_stream_V_full_n = img_1_data_stream_0_V_full_n;

assign image_filter_CvtColor_U0_p_src_data_stream_0_V_dout = img_0_data_stream_0_V_dout;

assign image_filter_CvtColor_U0_p_src_data_stream_0_V_empty_n = img_0_data_stream_0_V_empty_n;

assign image_filter_CvtColor_U0_p_src_data_stream_1_V_dout = img_0_data_stream_1_V_dout;

assign image_filter_CvtColor_U0_p_src_data_stream_1_V_empty_n = img_0_data_stream_1_V_empty_n;

assign image_filter_CvtColor_U0_p_src_data_stream_2_V_dout = img_0_data_stream_2_V_dout;

assign image_filter_CvtColor_U0_p_src_data_stream_2_V_empty_n = img_0_data_stream_2_V_empty_n;

assign image_filter_CvtColor_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_OUTPUT_STREAM_TREADY = OUTPUT_STREAM_TREADY;

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_continue = ap_sig_hs_continue;

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_ap_start = ap_start;

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_dout = img_2_data_stream_0_V_dout;

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_empty_n = img_2_data_stream_0_V_empty_n;

assign image_filter_Mat2AXIvideo_8_1080_1920_0_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_Resize_U0_ap_continue = ap_const_logic_1;

assign image_filter_Resize_U0_ap_start = ap_start;

assign image_filter_Resize_U0_cols = {{cols[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign image_filter_Resize_U0_p_dst_data_stream_V_full_n = img_2_data_stream_0_V_full_n;

assign image_filter_Resize_U0_p_src_data_stream_V_dout = img_1_data_stream_0_V_dout;

assign image_filter_Resize_U0_p_src_data_stream_V_empty_n = img_1_data_stream_0_V_empty_n;

assign image_filter_Resize_U0_rows = {{rows[(ap_const_lv32_B - 32'd1) : ap_const_lv32_0]}};

assign img_0_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_0_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_din;

assign img_0_data_stream_0_V_read = image_filter_CvtColor_U0_p_src_data_stream_0_V_read;

assign img_0_data_stream_0_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_0_V_write;

assign img_0_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_1_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_din;

assign img_0_data_stream_1_V_read = image_filter_CvtColor_U0_p_src_data_stream_1_V_read;

assign img_0_data_stream_1_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_1_V_write;

assign img_0_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_0_data_stream_2_V_din = image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_din;

assign img_0_data_stream_2_V_read = image_filter_CvtColor_U0_p_src_data_stream_2_V_read;

assign img_0_data_stream_2_V_write = image_filter_AXIvideo2Mat_U0_img_data_stream_2_V_write;

assign img_1_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_1_data_stream_0_V_din = image_filter_CvtColor_U0_p_dst_data_stream_V_din;

assign img_1_data_stream_0_V_read = image_filter_Resize_U0_p_src_data_stream_V_read;

assign img_1_data_stream_0_V_write = image_filter_CvtColor_U0_p_dst_data_stream_V_write;

assign img_2_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_2_data_stream_0_V_din = image_filter_Resize_U0_p_dst_data_stream_V_din;

assign img_2_data_stream_0_V_read = image_filter_Mat2AXIvideo_8_1080_1920_0_U0_img_data_stream_V_read;

assign img_2_data_stream_0_V_write = image_filter_Resize_U0_p_dst_data_stream_V_write;


endmodule //image_filter

