// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_AXIvideo2Mat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        rows,
        cols,
        img_data_stream_0_V_din,
        img_data_stream_0_V_full_n,
        img_data_stream_0_V_write,
        img_data_stream_1_V_din,
        img_data_stream_1_V_full_n,
        img_data_stream_1_V_write,
        img_data_stream_2_V_din,
        img_data_stream_2_V_full_n,
        img_data_stream_2_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 7'b1;
parameter    ap_ST_st2_fsm_1 = 7'b10;
parameter    ap_ST_st3_fsm_2 = 7'b100;
parameter    ap_ST_st4_fsm_3 = 7'b1000;
parameter    ap_ST_pp1_stg0_fsm_4 = 7'b10000;
parameter    ap_ST_st7_fsm_5 = 7'b100000;
parameter    ap_ST_st8_fsm_6 = 7'b1000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] INPUT_STREAM_TDATA;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
input  [3:0] INPUT_STREAM_TKEEP;
input  [3:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
input  [10:0] rows;
input  [10:0] cols;
output  [7:0] img_data_stream_0_V_din;
input   img_data_stream_0_V_full_n;
output   img_data_stream_0_V_write;
output  [7:0] img_data_stream_1_V_din;
input   img_data_stream_1_V_full_n;
output   img_data_stream_1_V_write;
output  [7:0] img_data_stream_2_V_din;
input   img_data_stream_2_V_full_n;
output   img_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg INPUT_STREAM_TREADY;
reg img_data_stream_0_V_write;
reg img_data_stream_1_V_write;
reg img_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm = 7'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_26;
reg   [0:0] eol_reg_186;
reg   [31:0] axi_data_V_1_i_reg_197;
reg   [10:0] p_2_i_reg_208;
reg   [0:0] eol_i_reg_219;
reg   [0:0] axi_last_V_2_i_reg_231;
reg   [31:0] p_Val2_s_reg_244;
reg    ap_sig_bdd_73;
reg   [31:0] tmp_data_V_reg_379;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_85;
reg   [0:0] tmp_last_V_reg_387;
wire   [0:0] exitcond8_i_fu_309_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_99;
wire   [10:0] i_V_fu_314_p2;
reg   [10:0] i_V_reg_403;
wire   [0:0] exitcond9_i_fu_320_p2;
reg   [0:0] exitcond9_i_reg_408;
reg    ap_sig_cseq_ST_pp1_stg0_fsm_4;
reg    ap_sig_bdd_110;
wire   [0:0] brmerge_i_fu_334_p2;
reg    ap_sig_bdd_118;
reg    ap_reg_ppiten_pp1_it0 = 1'b0;
reg    ap_sig_bdd_131;
reg    ap_reg_ppiten_pp1_it1 = 1'b0;
wire   [10:0] j_V_fu_325_p2;
wire   [7:0] tmp_fu_340_p1;
reg   [7:0] tmp_reg_421;
reg   [7:0] tmp_10_reg_426;
reg   [7:0] tmp_11_reg_431;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_bdd_156;
reg    ap_sig_bdd_161;
reg   [0:0] axi_last_V_3_i_reg_256;
reg   [0:0] axi_last_V1_i_reg_155;
reg    ap_sig_cseq_ST_st8_fsm_6;
reg    ap_sig_bdd_179;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_186;
reg   [31:0] axi_data_V_3_i_reg_268;
reg   [31:0] axi_data_V1_i_reg_165;
reg   [10:0] p_i_reg_175;
reg   [0:0] eol_phi_fu_189_p4;
reg   [31:0] axi_data_V_1_i_phi_fu_200_p4;
reg   [0:0] eol_i_phi_fu_223_p4;
wire   [0:0] ap_reg_phiprechg_axi_last_V_2_i_reg_231pp1_it0;
wire   [31:0] ap_reg_phiprechg_p_Val2_s_reg_244pp1_it0;
reg   [31:0] p_Val2_s_phi_fu_248_p4;
reg   [0:0] eol_2_i_reg_280;
reg   [0:0] sof_1_i_fu_100;
wire   [0:0] tmp_user_V_fu_300_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_sig_bdd_117;
reg    ap_sig_bdd_209;
reg    ap_sig_bdd_142;
reg    ap_sig_bdd_224;




always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp1_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp1_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond8_i_fu_309_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp1_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_data_V1_i_reg_165 <= tmp_data_V_reg_379;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_data_V1_i_reg_165 <= axi_data_V_3_i_reg_268;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        axi_data_V_1_i_reg_197 <= p_Val2_s_reg_244;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
        axi_data_V_1_i_reg_197 <= axi_data_V1_i_reg_165;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0))) begin
        axi_data_V_3_i_reg_268 <= axi_data_V_1_i_phi_fu_200_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_280) & ~ap_sig_bdd_161)) begin
        axi_data_V_3_i_reg_268 <= INPUT_STREAM_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        axi_last_V1_i_reg_155 <= tmp_last_V_reg_387;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        axi_last_V1_i_reg_155 <= axi_last_V_3_i_reg_256;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_142) begin
        if (ap_sig_bdd_209) begin
            axi_last_V_2_i_reg_231 <= eol_phi_fu_189_p4;
        end else if (ap_sig_bdd_117) begin
            axi_last_V_2_i_reg_231 <= INPUT_STREAM_TLAST;
        end else if ((ap_true == ap_true)) begin
            axi_last_V_2_i_reg_231 <= ap_reg_phiprechg_axi_last_V_2_i_reg_231pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0))) begin
        axi_last_V_3_i_reg_256 <= eol_phi_fu_189_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_280) & ~ap_sig_bdd_161)) begin
        axi_last_V_3_i_reg_256 <= INPUT_STREAM_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0))) begin
        eol_2_i_reg_280 <= eol_i_phi_fu_223_p4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_280) & ~ap_sig_bdd_161)) begin
        eol_2_i_reg_280 <= INPUT_STREAM_TLAST;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_i_reg_219 <= axi_last_V_2_i_reg_231;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
        eol_i_reg_219 <= ap_const_lv1_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        eol_reg_186 <= axi_last_V_2_i_reg_231;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
        eol_reg_186 <= axi_last_V1_i_reg_155;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        p_2_i_reg_208 <= j_V_fu_325_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
        p_2_i_reg_208 <= ap_const_lv11_0;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_bdd_142) begin
        if (ap_sig_bdd_209) begin
            p_Val2_s_reg_244 <= axi_data_V_1_i_phi_fu_200_p4;
        end else if (ap_sig_bdd_117) begin
            p_Val2_s_reg_244 <= INPUT_STREAM_TDATA;
        end else if ((ap_true == ap_true)) begin
            p_Val2_s_reg_244 <= ap_reg_phiprechg_p_Val2_s_reg_244pp1_it0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_i_reg_175 <= ap_const_lv11_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st8_fsm_6)) begin
        p_i_reg_175 <= i_V_reg_403;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        sof_1_i_fu_100 <= ap_const_lv1_0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        sof_1_i_fu_100 <= ap_const_lv1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        exitcond9_i_reg_408 <= exitcond9_i_fu_320_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        i_V_reg_403 <= i_V_fu_314_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        tmp_10_reg_426 <= {{p_Val2_s_phi_fu_248_p4[ap_const_lv32_F : ap_const_lv32_8]}};
        tmp_11_reg_431 <= {{p_Val2_s_phi_fu_248_p4[ap_const_lv32_17 : ap_const_lv32_10]}};
        tmp_reg_421 <= tmp_fu_340_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(INPUT_STREAM_TVALID == ap_const_logic_0))) begin
        tmp_data_V_reg_379 <= INPUT_STREAM_TDATA;
        tmp_last_V_reg_387 <= INPUT_STREAM_TLAST;
    end
end

always @ (INPUT_STREAM_TVALID or ap_sig_cseq_ST_st2_fsm_1 or exitcond9_i_fu_320_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or brmerge_i_fu_334_p2 or ap_sig_bdd_118 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_131 or ap_reg_ppiten_pp1_it1 or ap_sig_cseq_ST_st7_fsm_5 or ap_sig_bdd_161 or eol_2_i_reg_280) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(INPUT_STREAM_TVALID == ap_const_logic_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5) & (ap_const_lv1_0 == eol_2_i_reg_280) & ~ap_sig_bdd_161) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_fu_334_p2) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1)))))) begin
        INPUT_STREAM_TREADY = ap_const_logic_1;
    end else begin
        INPUT_STREAM_TREADY = ap_const_logic_0;
    end
end

always @ (ap_done_reg or exitcond8_i_fu_309_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond8_i_fu_309_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (exitcond8_i_fu_309_p2 or ap_sig_cseq_ST_st4_fsm_3) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(exitcond8_i_fu_309_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_110) begin
    if (ap_sig_bdd_110) begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp1_stg0_fsm_4 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_26) begin
    if (ap_sig_bdd_26) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_85) begin
    if (ap_sig_bdd_85) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_186) begin
    if (ap_sig_bdd_186) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_99) begin
    if (ap_sig_bdd_99) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_156) begin
    if (ap_sig_bdd_156) begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_179) begin
    if (ap_sig_bdd_179) begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_6 = ap_const_logic_0;
    end
end

always @ (axi_data_V_1_i_reg_197 or p_Val2_s_reg_244 or exitcond9_i_reg_408 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        axi_data_V_1_i_phi_fu_200_p4 = p_Val2_s_reg_244;
    end else begin
        axi_data_V_1_i_phi_fu_200_p4 = axi_data_V_1_i_reg_197;
    end
end

always @ (eol_i_reg_219 or axi_last_V_2_i_reg_231 or exitcond9_i_reg_408 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_i_phi_fu_223_p4 = axi_last_V_2_i_reg_231;
    end else begin
        eol_i_phi_fu_223_p4 = eol_i_reg_219;
    end
end

always @ (eol_reg_186 or axi_last_V_2_i_reg_231 or exitcond9_i_reg_408 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) begin
        eol_phi_fu_189_p4 = axi_last_V_2_i_reg_231;
    end else begin
        eol_phi_fu_189_p4 = eol_reg_186;
    end
end

always @ (exitcond9_i_reg_408 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_118 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_131 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_0_V_write = ap_const_logic_0;
    end
end

always @ (exitcond9_i_reg_408 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_118 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_131 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_1_V_write = ap_const_logic_0;
    end
end

always @ (exitcond9_i_reg_408 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_118 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_131 or ap_reg_ppiten_pp1_it1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_reg_408 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))))) begin
        img_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        img_data_stream_2_V_write = ap_const_logic_0;
    end
end

always @ (INPUT_STREAM_TDATA or brmerge_i_fu_334_p2 or axi_data_V_1_i_phi_fu_200_p4 or ap_reg_phiprechg_p_Val2_s_reg_244pp1_it0 or ap_sig_bdd_224) begin
    if (ap_sig_bdd_224) begin
        if (~(ap_const_lv1_0 == brmerge_i_fu_334_p2)) begin
            p_Val2_s_phi_fu_248_p4 = axi_data_V_1_i_phi_fu_200_p4;
        end else if ((ap_const_lv1_0 == brmerge_i_fu_334_p2)) begin
            p_Val2_s_phi_fu_248_p4 = INPUT_STREAM_TDATA;
        end else begin
            p_Val2_s_phi_fu_248_p4 = ap_reg_phiprechg_p_Val2_s_reg_244pp1_it0;
        end
    end else begin
        p_Val2_s_phi_fu_248_p4 = ap_reg_phiprechg_p_Val2_s_reg_244pp1_it0;
    end
end
always @ (ap_CS_fsm or INPUT_STREAM_TVALID or ap_sig_bdd_73 or exitcond8_i_fu_309_p2 or exitcond9_i_fu_320_p2 or ap_sig_bdd_118 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_131 or ap_reg_ppiten_pp1_it1 or ap_sig_bdd_161 or eol_2_i_reg_280 or tmp_user_V_fu_300_p1) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_73) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((~(INPUT_STREAM_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == tmp_user_V_fu_300_p1))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else if ((~(INPUT_STREAM_TVALID == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_user_V_fu_300_p1))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(exitcond8_i_fu_309_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_pp1_stg0_fsm_4 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end else if (((ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))) & ~(exitcond9_i_fu_320_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_4;
            end
        end
        ap_ST_st7_fsm_5 : 
        begin
            if (((ap_const_lv1_0 == eol_2_i_reg_280) & ~ap_sig_bdd_161)) begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end else if ((~ap_sig_bdd_161 & ~(ap_const_lv1_0 == eol_2_i_reg_280))) begin
                ap_NS_fsm = ap_ST_st8_fsm_6;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st8_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


assign ap_reg_phiprechg_axi_last_V_2_i_reg_231pp1_it0 = 'bx;

assign ap_reg_phiprechg_p_Val2_s_reg_244pp1_it0 = 'bx;


always @ (ap_CS_fsm) begin
    ap_sig_bdd_110 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end


always @ (exitcond9_i_fu_320_p2 or brmerge_i_fu_334_p2) begin
    ap_sig_bdd_117 = ((exitcond9_i_fu_320_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_fu_334_p2));
end


always @ (INPUT_STREAM_TVALID or exitcond9_i_fu_320_p2 or brmerge_i_fu_334_p2) begin
    ap_sig_bdd_118 = ((INPUT_STREAM_TVALID == ap_const_logic_0) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & (ap_const_lv1_0 == brmerge_i_fu_334_p2));
end


always @ (img_data_stream_0_V_full_n or img_data_stream_1_V_full_n or img_data_stream_2_V_full_n or exitcond9_i_reg_408) begin
    ap_sig_bdd_131 = (((img_data_stream_0_V_full_n == ap_const_logic_0) & (exitcond9_i_reg_408 == ap_const_lv1_0)) | ((exitcond9_i_reg_408 == ap_const_lv1_0) & (img_data_stream_1_V_full_n == ap_const_logic_0)) | ((exitcond9_i_reg_408 == ap_const_lv1_0) & (img_data_stream_2_V_full_n == ap_const_logic_0)));
end


always @ (ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_sig_bdd_118 or ap_reg_ppiten_pp1_it0 or ap_sig_bdd_131 or ap_reg_ppiten_pp1_it1) begin
    ap_sig_bdd_142 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0) & ~((ap_sig_bdd_118 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0)) | (ap_sig_bdd_131 & (ap_const_logic_1 == ap_reg_ppiten_pp1_it1))));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_156 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end


always @ (INPUT_STREAM_TVALID or eol_2_i_reg_280) begin
    ap_sig_bdd_161 = ((INPUT_STREAM_TVALID == ap_const_logic_0) & (ap_const_lv1_0 == eol_2_i_reg_280));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_179 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_186 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (exitcond9_i_fu_320_p2 or brmerge_i_fu_334_p2) begin
    ap_sig_bdd_209 = ((exitcond9_i_fu_320_p2 == ap_const_lv1_0) & ~(ap_const_lv1_0 == brmerge_i_fu_334_p2));
end


always @ (exitcond9_i_fu_320_p2 or ap_sig_cseq_ST_pp1_stg0_fsm_4 or ap_reg_ppiten_pp1_it0) begin
    ap_sig_bdd_224 = ((ap_const_logic_1 == ap_sig_cseq_ST_pp1_stg0_fsm_4) & (exitcond9_i_fu_320_p2 == ap_const_lv1_0) & (ap_const_logic_1 == ap_reg_ppiten_pp1_it0));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_26 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end


always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_73 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_85 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_99 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

assign brmerge_i_fu_334_p2 = (sof_1_i_fu_100 | eol_i_phi_fu_223_p4);

assign exitcond8_i_fu_309_p2 = (p_i_reg_175 == rows? 1'b1: 1'b0);

assign exitcond9_i_fu_320_p2 = (p_2_i_reg_208 == cols? 1'b1: 1'b0);

assign i_V_fu_314_p2 = (p_i_reg_175 + ap_const_lv11_1);

assign img_data_stream_0_V_din = tmp_reg_421;

assign img_data_stream_1_V_din = tmp_10_reg_426;

assign img_data_stream_2_V_din = tmp_11_reg_431;

assign j_V_fu_325_p2 = (p_2_i_reg_208 + ap_const_lv11_1);

assign tmp_fu_340_p1 = p_Val2_s_phi_fu_248_p4[7:0];

assign tmp_user_V_fu_300_p1 = INPUT_STREAM_TUSER;


endmodule //image_filter_AXIvideo2Mat

